// taller-react/src/app/components/header/Login.js
import React, { useState } from 'react';
import { useForm } from "react-hook-form";
import { useDispatch } from 'react-redux';
import { setUser, login, setFavourites, setFavouritesId } from '../../../features/counter/counterSlice';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';
import Modal from 'react-bootstrap/Modal';

export const Login = () => {
    const [showLoginModal, setShowLoginModal] = useState(false);
    const [errorMessage, setErrorMessage] = useState('');
    const { register, handleSubmit, formState } = useForm({ mode: "onChange" });
    const dispatch = useDispatch();

    const handleCloseLoginModal = () => setShowLoginModal(false);
    const handleShowLoginModal = () => setShowLoginModal(true);

    async function fetchUserFavourites(userId) {
        const res = await fetch(`http://localhost:3004/favourites?userId=${userId}`);
        res.json().then(res => {
            dispatch(setFavourites(res[0].favouriteProducts));
            dispatch(setFavouritesId(res[0].id));
        });
    }

    async function fetchUser(formData) {
        const res = await fetch(`http://localhost:3004/users?userEmail=${formData.loginEmail}`);
        res.json().then(res => {
            if (res.length > 0) {
                setErrorMessage('');
                if (res[0].userPassword === formData.loginPassword) {
                    dispatch(setUser(res[0]));
                    fetchUserFavourites(res[0].id);
                    dispatch(login());
                    handleCloseLoginModal();
                } else {
                    setErrorMessage('Los datos introducidos no son correctos.');
                }
            } else {
                setErrorMessage('No existe nigún usuario con ese correo electrónico.');
            }
        });
    }

    const loginSubmit = (formData) => {
        fetchUser(formData);
    }


    return (
        <React.Fragment>
            <button type="button" className="btn btn-danger px-4 ml-2" onClick={handleShowLoginModal}>Entrar</button>
            <Modal show={showLoginModal} onHide={handleCloseLoginModal}>
                <Modal.Body className="p-5 text-center">
                    <h2 className="mb-5">¡Bienvenido!</h2>
                    <form onSubmit={handleSubmit(loginSubmit)}>
                        <div className="form-group mt-5">
                            <label htmlFor="email" className="mb-1 h5">Correo electrónico</label>
                            <input type="email" className="form-control" name="loginEmail" id="loginEmail" ref={register({ required: true })} />
                        </div>
                        <div className="form-group">
                            <label htmlFor="password" className="mb-1 h5">Contraseña</label>
                            <input type="password" className="form-control" name="loginPassword" id="loginPassword" ref={register({ required: true })} />
                        </div>
                        {errorMessage && <p className="mb-0 text-danger small">{errorMessage}</p>}
                        <div className="row m-0 mt-5 justify-content-center">
                            <button type="button" className="col-4 btn btn-outline-danger mr-2"
                                id="closeLoginModal" onClick={handleCloseLoginModal}>Cerrar</button>
                            <button type="submit" disabled={!formState.isValid} className="col-4 btn btn-dark ml-2">Entrar</button>
                        </div>
                    </form>
                </Modal.Body>
            </Modal>
        </React.Fragment>
    );
};

// taller-angular/src/app/components/login/login.component.ts
import { Component, OnInit, EventEmitter, Output, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subscription } from 'rxjs';
import { appActions } from '../../store/app.actions';
import { UserService } from '../../services/user.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { appState } from '../../store/app.state.interface';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit, OnDestroy {

  public loginForm: FormGroup;
  public errorMessage: string;
  private subscription: Subscription = new Subscription();

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private store: Store<appState>) { }

  ngOnInit(): void {
    this.createForm();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private createForm(): void {
    this.loginForm = this.fb.group({
      email: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  private solveSuccessfulLogin(user: any): void {
    this.resetForm();
    this.store.dispatch(appActions.login());
    this.store.dispatch(appActions.setUser(user));
    this.getUserFavourites(user.id);
    document.getElementById('closeLoginModal').click();
  }

  private getUserFavourites(userId: number) {
    this.subscription.add(
      this.userService.getUserFavourites(userId).subscribe((userFavourites: any) => {
        this.store.dispatch(appActions.setFavourites({ favourites: (userFavourites.length>0)?userFavourites[0].favouriteProducts:[] }));
        this.store.dispatch(appActions.setFavouritesId({ favouritesId: (userFavourites.length>0)?userFavourites[0].id:0 }));
      })
    );
  }

  private resetForm() {
    this.loginForm.reset();
    this.errorMessage = '';
  }

  public login(): void {
    this.subscription.add(
      this.userService.getUserByEmail(this.loginForm.get('email').value).subscribe((data: any) => {
        if (data.length == 0 || data[0].userPassword !== this.loginForm.get('password').value) {
          this.errorMessage = 'El usuario introducido no existe o los datos no son correctos.'
        } else {
          this.solveSuccessfulLogin(data[0]);
        }
      })
    );
  }

}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body p-5 text-center">
            <h2 class="mb-5">¡Bienvenido!</h2>
            <form [formGroup]="loginForm" (ngSubmit)="login()">
                <div class="form-group mt-5">
                    <label for="email" class="mb-1 h5">Correo electrónico</label>
                    <input formControlName="email" type="email" class="form-control" id="loginEmail" required>
                </div>
                <div class="form-group">
                    <label for="password" class="mb-1 h5">Contraseña</label>
                    <input formControlName="password" type="password" class="form-control" id="loginPassword" required>
                    <small class="form-text text-danger">{{errorMessage}}</small>
                </div>
                <div class="row m-0 mt-5 justify-content-center">
                    <button type="button" class="col-4 btn btn-outline-danger mr-2" data-dismiss="modal"
                        id="closeLoginModal">Cerrar</button>
                    <button type="submit" [disabled]="!loginForm.valid" class="col-4 btn btn-dark ml-2">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
