// taller-react/src/app/components/Product.js
import React from 'react';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';
import Card from 'react-bootstrap/Card';

export const Product = ({productData}) => {
    return (
        <div className="col-12 col-sm-6 col-md-4 col-xl-3 p-2">
            <Card className="product-card m-0 p-0">
                <Card.Img variant="top" className="p-3" src={productData.productImage} alt={productData.productName} />
                <Card.Body className="p-3 text-center">
                    <h5 className="mb-0">{productData.productName}</h5>
                    <p className="card-text mb-0">{productData.productResume}</p>
                    <p className="mb-0 font-weight-bold h4">{productData.productPrice}€</p>
                </Card.Body>
            </Card>
        </div>
    );
};

// taller-angular/src/app/components/product/product.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.scss']
})
export class ProductComponent implements OnInit {
  @Input() product: any;

  constructor() { }

  ngOnInit(): void { }

}

<div class="card mx-2">
    <img class=" img-fluid px-3 pt-3" [src]="product.productImage" [alt]="product.name">
    <div class="card-body p-3 text-center">
        <h5 class="mb-0">{{product.productName}}</h5>
        <p class="card-text mb-0">{{product.productResume}}</p>
        <p class="mb-0 font-weight-bold h4">{{product.productPrice}}€</p>
    </div>
</div>
