// taller-react/src/app/components/Search.js
import React, { useState, useEffect } from 'react';
import { useForm } from "react-hook-form";
import { useDispatch } from 'react-redux';
import { setFilteredProducts } from '../../features/counter/counterSlice';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';

export const Search = () => {
    const [products, setProducts] = useState([]);
    let filteredProducts = [];
    const [brands, setBrands] = useState([]);
    const [prices, setPrices] = useState([[]]);
    const { register, handleSubmit } = useForm();
    const dispatch = useDispatch();


    const createPricesArray = () => {
        setPrices([[0, 200], [200, 400], [400, 750], [750, 1000], [1000]]);
    }

    const getBrands = async () => {
        const res = await fetch(`http://localhost:3004/brands`);
        res.json().then(res => {
            setBrands(res);
        });
    }

    const getProducts = async () => {
        const res = await fetch(`http://localhost:3004/products`);
        res.json().then(res => {
            dispatch(setFilteredProducts(res));
            setProducts(res);
        });
    }

    const filterByUser = (unfilteredProducts, userFilter) => {
        return unfilteredProducts.filter((product) => (product.productName.toUpperCase()).includes(userFilter.toUpperCase().trim()));
    }

    const filterByBrand = (unfilteredProducts, brandFilter) => {
        return unfilteredProducts.filter((product) => (product.productBrand).includes(brandFilter));
    }

    const filterByPrice = (unfilteredProducts, priceFilter) => {
        return unfilteredProducts.filter((product) => {
            if (prices[priceFilter].length > 1) {
                return product.productPrice >= prices[priceFilter][0] && product.productPrice < prices[priceFilter][1];
            } else {
                return product.productPrice >= prices[priceFilter][0];
            }
        });
    }

    const applyFilters = (filters) => {
        if (filters.userFilter) {
            filteredProducts = filterByUser(filteredProducts, filters.userFilter);
        }
        if (filters.brandFilter !== 'noBrandFilter') {
            filteredProducts = filterByBrand(filteredProducts, filters.brandFilter);
        }
        if (filters.priceFilter !== 'noPriceFilter') {
            filteredProducts = filterByPrice(filteredProducts, filters.priceFilter);
        }
    }

    useEffect(() => {
        getProducts();
        getBrands();
        createPricesArray();
    }, []);

    const searchSubmit = (formData) => {
        filteredProducts = products;
        applyFilters(formData);
        dispatch(setFilteredProducts(filteredProducts));
    }

    return (
        <form onSubmit={handleSubmit(searchSubmit)} className="row m-0 p-3 mb-5 bg-light">
            <div className="col-12 col-lg-5 col-xl-4 px-0 pr-lg-1">
                <input className="form-control text-center border-dark" type="search" placeholder="¿Qué estás buscando?"
                    aria-label="Search" name="userFilter" ref={register} />
            </div>
            <div className="col-6 col-md-4 col-lg-3 px-0 pr-2 py-3 pb-md-0 pt-lg-0 px-lg-1">
                <select className="pl-3 custom-select text-center border-dark" name="brandFilter" ref={register}>
                    <option value='noBrandFilter' defaultValue>¿De qué marca?</option>
                    {
                        brands.map((brand, index) => <option key={index} value={brand}>{brand}</option>)
                    }
                </select>
            </div>
            <div className="col-6 col-md-4 col-lg-3 px-0 pl-2 pr-md-2 py-3 pb-md-0 pt-lg-0 px-lg-1">
                <select className="pl-3 custom-select border-dark" name="priceFilter" ref={register}>
                    <option className="text-center" value='noPriceFilter' defaultValue>¿De qué precio?</option>
                    {prices.map((item, index) =>
                        <option key={index} value={index}>
                            De {item[0]} a {item[1]}€
                        </option>
                    )}
                </select>
            </div >
            <div className="col-6 col-md-4 col-lg-1 col-xl-2 px-0 pl-md-2 pt-md-3 pt-lg-0 pl-lg-1 mx-auto">
                <button type="subtmit" className="btn btn-outline-dark btn-block"><span className="font-weight-bold">Buscar</span></button>
            </div>
        </form>
    );
};

// taller-angular/src/app/components/search/search.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription, VirtualTimeScheduler } from 'rxjs';
import { Product } from 'src/app/models/product.model';
import { ProductService } from '../../services/product.service';
import { ShareDataService } from '../../services/share-data.service';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit, OnDestroy {

  private subscription: Subscription = new Subscription();
  private products: Product[];
  public userFilter: string;
  public brandFilter: string = 'noBrandFilter';
  public priceFilter: string = 'noPriceFilter';
  public filteredProducts: Product[];
  public brands: string[];
  public prices: number[][];

  constructor(
    private productService: ProductService,
    private shareService: ShareDataService
  ) { }

  ngOnInit(): void {
    this.subscribeProducts();
    this.subscribeBrands();
    this.createPricesArray();
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  private createPricesArray() {
    this.prices = [[0, 200], [200, 400], [400, 750], [750, 1000], [1000]];
  }

  private subscribeProducts(): void {
    this.subscription.add(
      this.productService.getProducts().subscribe((productsData: Product[]) => {
        this.products = productsData;
        this.shareService.updateProducts(this.products);
      })
    );
  }

  private subscribeBrands(): void {
    this.subscription.add(
      this.productService.getBrands().subscribe((brandsData: string[]) => {
        this.brands = brandsData.sort();
      })
    );
  }

  private filterByUser(unfilteredProducts: Product[]): Product[] {
    return unfilteredProducts.filter((product: Product) => (product.productName.toUpperCase()).includes(this.userFilter.toUpperCase().trim()));
  }

  private filterByBrand(unfilteredProducts: Product[]): Product[] {
    return unfilteredProducts.filter((product: Product) => (product.productBrand).includes(this.brandFilter));
  }

  private filterByPrice(unfilteredProducts: Product[]): Product[] {
    return unfilteredProducts.filter((product: Product) => {
      if (this.prices[this.priceFilter].length > 1) {
        return product.productPrice >= this.prices[this.priceFilter][0] && product.productPrice < this.prices[this.priceFilter][1];
      } else {
        return product.productPrice >= this.prices[this.priceFilter][0];
      }
    });
  }

  private applyFilters() {
    if (this.userFilter) {
      this.filteredProducts = this.filterByUser(this.filteredProducts);
    }
    if (this.brandFilter !== 'noBrandFilter') {
      this.filteredProducts = this.filterByBrand(this.filteredProducts);
    }
    if (this.priceFilter !== 'noPriceFilter') {
      this.filteredProducts = this.filterByPrice(this.filteredProducts);
    }
  }

  public filterProducts(): void {
    this.filteredProducts = this.products;
    this.applyFilters();
    this.shareService.updateProducts(this.filteredProducts);
  }

}

<div class="row m-0 p-3 mb-5 bg-light">
    <div class="col-12 col-lg-5 col-xl-4 px-0 pr-lg-1">
        <input class="form-control text-center border-dark" type="search" placeholder="¿Qué estás buscando?"
            aria-label="Search" [(ngModel)]="userFilter">
    </div>
    <div class="col-6 col-md-4 col-lg-3 px-0 pr-2 py-3 pb-md-0 pt-lg-0 px-lg-1">
        <select class="pl-3 custom-select text-center border-dark" [(ngModel)]="brandFilter">
            <option value='noBrandFilter' selected>¿De qué marca?</option>
            <option *ngFor="let brand of brands" [value]="brand">{{brand}}</option>
        </select>
    </div>
    <div class="col-6 col-md-4 col-lg-3 px-0 pl-2 pr-md-2 py-3 pb-md-0 pt-lg-0 px-lg-1">
        <select class="pl-3 custom-select border-dark" [(ngModel)]="priceFilter">
            <option class="text-center" value='noPriceFilter' selected>¿De qué precio?</option>
            <option *ngFor="let priceInterval of prices;index as i" [value]="i">
                <span *ngIf="priceInterval.length&gt;1">De {{priceInterval[0]}} a {{priceInterval[1]}}€</span>
                <span *ngIf="priceInterval.length&lt;2">Más de {{priceInterval[0]}}€</span>
            </option>
        </select>
    </div>
    <div class="col-6 col-md-4 col-lg-1 col-xl-2 px-0 pl-md-2 pt-md-3 pt-lg-0 pl-lg-1 mx-auto">
        <button type="button" class="btn btn-outline-dark btn-block" (click)="filterProducts()"><span class="font-weight-bold">Buscar</span></button>
    </div>
</div>
