// taller-angular/src/app/pages/favourites-page/favourites-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-favourites-page',
  templateUrl: './favourites-page.component.html',
  styleUrls: ['./favourites-page.component.scss']
})
export class FavouritesPageComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="row m-0 flex-xl-row-reverse">
    <div class="col-12 col-xl-3 px-0 pl-xl-4">
        <app-sidebar></app-sidebar>
    </div>
    <div class="col-12 col-xl-9 px-0 pr-xl-4">
        <p *ngIf="products.length&lt;1" class="mx-auto text-center h2 py-5 my-5">Aún no tienes productos favoritos</p>
        <section *ngIf="products.length&gt;0" class="card-deck m-0 px-4 p-sm-2 bg-light">
            <app-product *ngFor="let product of products" [product]="product"
                class="col-12 col-sm-6 col-md-4 col-xl-3 p-2"></app-product>
        </section>
    </div>
</div>

// taller-react/src/app/pages/FavouritesPage.js
import React from 'react';
import { useSelector } from 'react-redux';
import { selectFavourites } from '../../features/counter/counterSlice';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';
import CardDeck from 'react-bootstrap/CardDeck';

/* Children components */
import { Sidebar } from '../components/Sidebar';
import { Product } from '../components/Product';

export const FavouritesPage = () => {
    const favourites = useSelector(selectFavourites);
    
    return (
        <div className="row m-0 flex-xl-row-reverse">
            <div className="col-12 col-xl-3 px-0 pl-xl-4">
                <Sidebar></Sidebar>
            </div>
            <div className="col-12 col-xl-9 px-0 pr-xl-4">
                {(favourites.length > 0)
                    ?
                    <CardDeck className="m-0 px-4 p-sm-2 bg-light">
                        {favourites.map((item, index) => <Product key={index} productData={item} />)}
                    </CardDeck>
                    :
                    <p className="mx-auto text-center h2 py-5 my-5">Aún no tienes productos favoritos.</p>
                }
            </div>
        </div>
    );
};
