// taller-angular/src/app/pages/product-list-page/product-list-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { ShareDataService } from '../../services/share-data.service';
import { Product } from '../../models/product.model';

@Component({
  selector: 'app-product-list-page',
  templateUrl: './product-list-page.component.html',
  styleUrls: ['./product-list-page.component.scss']
})
export class ProductListPageComponent implements OnInit {

  private subscription: Subscription = new Subscription();
  public products: Product[];

  constructor(private shareService: ShareDataService) { }

  ngOnInit(): void {
    this.getProductList();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private getProductList() {
    this.subscription.add(
      this.shareService.filteredProducts.subscribe((data: Product[]) => {
        this.products = data;
      })
    );
  }

}

<div class="row m-0 flex-xl-row-reverse">
    <div class="col-12 col-xl-3 px-0 pl-xl-4">
        <app-sidebar></app-sidebar>
    </div>
    <div class="col-12 col-xl-9 px-0 pr-xl-4">
        <app-search></app-search>
        <p *ngIf="products.length&lt;1" class="mx-auto text-center h2 py-5 my-5">Parece que ningún producto coincide con
            lo que buscas...
        </p>
        <section *ngIf="products.length&gt;0" class="card-deck m-0 px-4 p-sm-2 bg-light">
            <app-product *ngFor="let product of products" [product]="product" class="col-12 col-sm-6 col-md-4 col-xl-3 p-2"></app-product>
        </section>
    </div>
</div>

// taller-react/src/app/pages/ProductListPage.js
import React from 'react';
import { useSelector } from 'react-redux';
import { selectFilteredProducts } from '../../features/counter/counterSlice';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';
import CardDeck from 'react-bootstrap/CardDeck';

/* Children components */
import { Sidebar } from '../components/Sidebar';
import { Search } from '../components/Search';
import { Product } from '../components/Product';

export const ProductListPage = () => {
    const products = useSelector(selectFilteredProducts);

    return (
        <div className="row m-0 flex-xl-row-reverse">
            <div className="col-12 col-xl-3 px-0 pl-xl-4">
                <Sidebar></Sidebar>
            </div>
            <div className="col-12 col-xl-9 px-0 pr-xl-4">
                <Search />
                {(products.length > 0)
                    ?
                    <CardDeck className="m-0 px-4 p-sm-2 bg-light">
                        {products.map((item, index) => <Product key={index} productData={item} />)}
                    </CardDeck>
                    :
                    <p className="mx-auto text-center h2 py-5 my-5">Parece que ningún producto coincide con lo que buscas...</p>
                }
            </div >
        </div>
    );
};
