// taller-react/src/app/components/header/Registration.js
import React, { useState } from 'react';
import { useForm } from "react-hook-form";
import { useDispatch } from 'react-redux';
import { setUser, login } from '../../../features/counter/counterSlice';

/* Bootstrap imports */
import 'bootstrap/dist/css/bootstrap.min.css';
import Modal from 'react-bootstrap/Modal';

export const Registration = () => {
    const [showRegistrationModal, setShowRegistrationModal] = useState(false);
    const [errorMessage, setErrorMessage] = useState('');
    const { register, handleSubmit, formState } = useForm({ mode: "onChange" });
    const dispatch = useDispatch();

    const handleCloseRegistrationModal = () => setShowRegistrationModal(false);
    const handleShowRegistrationModal = () => setShowRegistrationModal(true);

    const createUserObject = (formData) => {
        return {
            "userName": formData.registrationName,
            "userSurname": formData.registrationSurname,
            "userEmail": formData.registrationEmail,
            "userPassword": formData.registrationPassword,
        };
    }

    const createUser = async (formData) => {
        const res = await fetch(`http://localhost:3004/users`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(createUserObject(formData))
        });
        res.json().then(res => {
            dispatch(setUser(res));
            dispatch(login());
            handleCloseRegistrationModal();
        });
    }

    async function fetchUser(formData) {
        const res = await fetch(`http://localhost:3004/users?userEmail=${formData.registrationEmail}`);
        res.json().then(res => {
            if (res.length === 0) {
                createUser(formData);
            } else {
                setErrorMessage('Ya existe un usuario con ese correo electrónico.');
            }
        });
    }

    const RegistrationSubmit = (formData) => {
        if (formData.registrationPassword !== formData.confirmedRegistrationPassword) {
            setErrorMessage('Las contraseñas deben coincidir.');
        } else {
            fetchUser(formData);
        }
    }

    return (
        <React.Fragment>
            <button type="button" className="btn btn-outline-light px-4 mr-2" onClick={handleShowRegistrationModal}>Registrarse</button>
            <Modal show={showRegistrationModal} onHide={handleCloseRegistrationModal}>
                <Modal.Body className="p-5 text-center">
                    <h2 className="mb-5">¡Bienvenido!</h2>
                    <form onSubmit={handleSubmit(RegistrationSubmit)}>
                        <div class="form-group">
                            <label htmlFor="registrationName" class="mb-1 h5">Nombre</label>
                            <input type="text" class="form-control" name="registrationName" id="registrationName" ref={register({ required: true })} />
                        </div>
                        <div class="form-group">
                            <label htmlFor="registrationSurname" class="mb-1 h5">Apellidos</label>
                            <input type="text" class="form-control" name="registrationSurname" id="registrationSurname" ref={register({ required: true })} />
                        </div>
                        <div class="form-group">
                            <label htmlFor="registrationEmail" class="mb-1 h5">Correo electrónico</label>
                            <input type="email" class="form-control" name="registrationEmail" id="registrationEmail" ref={register({ required: true })} />
                        </div>
                        <div class="form-group">
                            <label htmlFor="registrationPassword" class="mb-1 h5">Contraseña</label>
                            <input type="password" class="form-control" name="registrationPassword" id="registrationPassword" ref={register({ required: true })} />
                        </div>
                        <div class="form-group">
                            <label htmlFor="confirmedRegistrationPassword" class="mb-1 h5">Confirma la contraseña</label>
                            <input type="password" class="form-control" name="confirmedRegistrationPassword" id="confirmedRegistrationPassword" ref={register({ required: true })} />
                        </div>
                        {errorMessage && <p class="mb-0 text-danger small">{errorMessage}</p>}
                        <div class="row m-0 mt-5 justify-content-center">
                            <button type="button" class="col-4 btn btn-outline-danger mr-2" id="closeRegistrationModal" onClick={handleCloseRegistrationModal}>Cerrar</button>
                            <button type="submit" disabled={!formState.isValid} class="col-4 btn btn-dark ml-2">Registrarse</button>
                        </div>
                    </form>
                </Modal.Body>
            </Modal>
        </React.Fragment>
    );
};

// taller-angular/src/app/components/registration/registration.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from '../../services/user.service';
import { appState } from '../../store/app.state.interface';
import { Store } from '@ngrx/store';
import { appActions } from '../../store/app.actions';
import { User } from '../../models/user.model';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.scss']
})
export class RegistrationComponent implements OnInit, OnDestroy {

  public registrationForm: FormGroup;
  private subscription: Subscription = new Subscription();
  public errorMessage: string;

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private store: Store<appState>
  ) { }

  ngOnInit(): void {
    this.createForm();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private createForm(): void {
    this.registrationForm = this.fb.group({
      name: ['', Validators.required],
      surname: ['', Validators.required],
      email: ['', Validators.required],
      password: ['', Validators.required],
      confirmedPassword: ['', Validators.required]
    });
  }

  private solveSuccessfulRegister(user: any): void {
    this.registrationForm.reset();
    this.store.dispatch(appActions.login());
    this.store.dispatch(appActions.setUser(user));
    document.getElementById('closeRegistrationModal').click();
  }

  private createUserObject(): User {
    return {
      "userName": this.registrationForm.get('name').value,
      "userSurname": this.registrationForm.get('surname').value,
      "userEmail": this.registrationForm.get('email').value,
      "userPassword": this.registrationForm.get('password').value,
    };
  }

  private createUser(userObject: User) {
    this.subscription.add(
      this.userService.addNewUser(userObject).subscribe((newUser: User) => {
        this.solveSuccessfulRegister(newUser);
      })
    );
  }

  private checkEmail() {
    this.subscription.add(
      this.userService.getUserByEmail(this.registrationForm.get('email').value).subscribe((data: any) => {
        if (data.length === 0) {
          this.errorMessage = '';
          this.createUser(this.createUserObject());
        } else {
          this.errorMessage = 'Ya existe un usuario con ese correo';
        }
      })
    );
  }

  public register() {
    if (this.registrationForm.get('password').value !== this.registrationForm.get('confirmedPassword').value) {
      this.errorMessage = 'Las contraseñas deben coincidir';
    } else {
      this.errorMessage = '';
      this.checkEmail();
    }
  }

}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body p-5">
            <h2 class="mb-5 text-center">¡Bienvenido!</h2>
            <form [formGroup]="registrationForm" (ngSubmit)="register()">
            <div class="form-group">
                <label for="registrationName" class="mb-1 h5">Nombre</label>
                <input formControlName="name" type="text" class="form-control" id="registrationName" required>
            </div>
            <div class="form-group">
                <label for="registrationSurname" class="mb-1 h5">Apellidos</label>
                <input formControlName="surname" type="text" class="form-control" id="registrationSurname" required>
            </div>
            <div class="form-group">
                <label for="registrationEmail" class="mb-1 h5">Correo electrónico</label>
                <input formControlName="email" type="email" class="form-control" id="registrationEmail" required>
            </div>
            <div class="form-group">
                <label for="registrationPassword" class="mb-1 h5">Contraseña</label>
                <input formControlName="password" type="password" class="form-control" id="registrationPassword" required>
            </div>
            <div class="form-group">
                <label for="confirmedRegistrationPassword" class="mb-1 h5">Confirma la contraseña</label>
                <input formControlName="confirmedPassword" type="password" class="form-control" id="confirmedRegistrationPassword" required>
            </div>
            <p *ngIf="errorMessage && errorMessage.length>0" class="mb-0 text-danger">{{errorMessage}}</p>
            <div class="row m-0 mt-5 justify-content-center">
                <button type="button" class="col-4 btn btn-outline-danger mr-2" data-dismiss="modal" id="closeRegistrationModal">Cerrar</button>
                <button type="submit" [disabled]="!registrationForm.valid" class="col-4 btn btn-dark ml-2">Registrarse</button>
            </div>
        </form>
        </div>
    </div>
</div>
